# Generated by Django 4.0.4 on 2022-05-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EmailID', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=200)),
                ('person_id', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
