# Generated by Django 4.0.4 on 2022-05-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_vendor_aadharcard_vendor_address_vendor_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='PasswordReset',
            field=models.BooleanField(default=False),
        ),
    ]
